{
  "errorCode" : "NOT_FOUND",
  "messages" : [ "Object not found" ],
  "dataErrors" : [ ],
  "attributes" : {
    "traceId" : "40e1488ed0001adc",
    "exception" : "TestObjectNotFoundException",
    "startTime" : "2020-11-27T11:17:40.095818Z"
  }
}