{
  "errorCode" : "ERROR_CODE",
  "messages" : [ "Exception message" ],
  "dataErrors" : [ ],
  "attributes" : {
    "traceId" : "40e1488ed0001adc",
    "exception" : "TestException",
    "startTime" : "2020-11-27T11:17:40.095818Z"
  }
}